server:
  port: 8080

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC

mybatis:
  type-aliases-package: com.shen.demo.dao
  mapper-locations: classpath:mapper/*.xml

custom:
  isPrintExceptionStack: true